### PR TITLE
Makefile: Turn off --as-needed for libudev.so.1

### PR DESCRIPTION
**Pull request by evelikov**
The option can be enabled by default, thus the shim will end without the
DT_NEEDED entry against libudev.so.1.

Patch inspired by Debian.

### CODE REVIEW

**Comment by smcv** [comment]
I'm not a maintainer, but I've been looking at libudev0-shim as a way to resolve some Steam crashes, and this change looks good to me. I confirm that `-Wl,--no-as-needed` is necessary when using the system compiler in Debian/Ubuntu, which defaults to the equivalent of `-Wl,--as-needed` to mitigate over-linking.

[Gentoo's equivalent of this shim](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-libs/libudev-compat) is also linked with `-Wl,--no-as-needed` for similar reasons.

**Comment by evelikov** [comment]
Tagging some Arch people @falconindy @grazzolini @Foxboron @anthraxx 

Without this fix the resulting library is effectively borked, since the libudev.so.1 link will be automatically removed and the symbols required by users will be missing/unresolved.

**Comment by smcv** [comment]
The version of libudev0-shim packaged in Debian by @GyrosGeier has had a patch equivalent to this one since 2020, and it seems to work well.

Since August 2023, the Steam Runtime contains a version of libudev0-shim derived from the one in Debian, therefore also carrying a patch equivalent to this one.

It would be great if this could be fixed in a new upstream release so that distros do not need to apply patches.

**Comment by evelikov** [comment]
Rebased on top of #4 and merging.

**Pull request merged**
